apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      serviceAccountName: jenkins
      containers:
      - name: bankapp
        image: giri8608/bankapp:latest
        ports:
        - containerPort: 8080
